on:
  workflow_dispatch:

permissions: 
  id-token: write
  pages: write
  contents: read

concurrency: 
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy repository manifest
    runs-on: ubuntu-latest
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Generate vpm.json
        uses: actions/github-script@7
        with:
          script: return "Hello!"
      
