on:
  workflow_dispatch:

permissions: 
  id-token: write
  pages: write
  contents: read

concurrency: 
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy repository manifest
    runs-on: ubuntu-latest
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Generate vpm.json
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const rsf = require('fs')
              const jsonString = rsf.readFileSync('packages/vpm-test/vpm-test-1.0.0.json')
              core.info(jsonString)
            } catch(err) {
              core.error("Error while reading or parsing the JSON")
              core.setFailed(err)
            }
      
